expert_happiness_dest_dir: /opt/rackspace/expert-happiness
expert_happiness_pip_packages: []
horizon_venv_bin: "/openstack/venvs/horizon-{{ openstack_release }}/bin"
horizon_venv_lib_dir: "{{ horizon_venv_bin | dirname }}/lib/python2.7/dist-packages"
horizon_system_user_name: horizon
